services:
  - type: web
    name: chatbot.
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: HUBSPOT_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    plan: free 
